# Generated by Django 6.0.2 on 2026-02-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=100)),
                ('meta_regime', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'decisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('position_size', models.FloatField(default=0.0)),
                ('average_price', models.FloatField(default=0.0)),
                ('exposure', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capital', models.FloatField(default=0.0)),
                ('used_capital', models.FloatField(default=0.0)),
                ('free_capital', models.FloatField(default=0.0)),
                ('total_exposure', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capital', models.FloatField(default=100000)),
                ('risk_per_trade', models.FloatField(default=0.02)),
                ('max_exposure_per_asset', models.FloatField(default=0.2)),
                ('max_total_exposure', models.FloatField(default=0.8)),
                ('atr_multiplier', models.FloatField(default=1.5)),
                ('kelly_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('position_size', models.FloatField()),
                ('price', models.FloatField()),
                ('capital_allocated', models.FloatField()),
                ('meta_regime', models.CharField(max_length=50)),
                ('strategy', models.CharField(max_length=100)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trade Execution',
                'verbose_name_plural': 'Trade Executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
