# Generated by Django 6.0.2 on 2026-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capital', models.FloatField(default=100000)),
                ('risk_per_trade', models.FloatField(default=0.02)),
                ('max_exposure_per_asset', models.FloatField(default=0.2)),
                ('max_total_exposure', models.FloatField(default=0.8)),
                ('atr_multiplier', models.FloatField(default=1.5)),
                ('kelly_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
