# Generated by Django 6.0.2 on 2026-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('position_size', models.FloatField(default=0.0)),
                ('average_price', models.FloatField(default=0.0)),
                ('exposure', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capital', models.FloatField(default=0.0)),
                ('used_capital', models.FloatField(default=0.0)),
                ('free_capital', models.FloatField(default=0.0)),
                ('total_exposure', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
