# Generated by Django 6.0.2 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_portfolioposition_portfoliosummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=100)),
                ('meta_regime', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'decisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('position_size', models.FloatField()),
                ('price', models.FloatField()),
                ('capital_allocated', models.FloatField()),
                ('meta_regime', models.CharField(max_length=50)),
                ('strategy', models.CharField(max_length=100)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trade Execution',
                'verbose_name_plural': 'Trade Executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
